

version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies for server-side code
     - cd backend && npm install
      # Install dependencies for client-side code
     - cd ../frontend && npm install
  build:
    commands:
      # Build client-side code
      - npm run build
    
artifacts:
  files:
    - '**/*'
  discard-paths: no  
  base-directory: ./
  


